// source: service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var custom_types_pb = require('./custom_types_pb.js');
goog.object.extend(proto, custom_types_pb);
var transactions_pb = require('./transactions_pb.js');
goog.object.extend(proto, transactions_pb);
goog.exportSymbol('proto.votings_service.Config', null, global);
goog.exportSymbol('proto.votings_service.TxStoreBallotCopy', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.votings_service.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.votings_service.Config.repeatedFields_, null);
};
goog.inherits(proto.votings_service.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.votings_service.Config.displayName = 'proto.votings_service.Config';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.votings_service.TxStoreBallotCopy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.votings_service.TxStoreBallotCopy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.votings_service.TxStoreBallotCopy.displayName = 'proto.votings_service.TxStoreBallotCopy';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.votings_service.Config.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.votings_service.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.votings_service.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.votings_service.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.votings_service.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    apiPublicKeysList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.votings_service.Config}
 */
proto.votings_service.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.votings_service.Config;
  return proto.votings_service.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.votings_service.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.votings_service.Config}
 */
proto.votings_service.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addApiPublicKeys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.votings_service.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.votings_service.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.votings_service.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.votings_service.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApiPublicKeysList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string api_public_keys = 1;
 * @return {!Array<string>}
 */
proto.votings_service.Config.prototype.getApiPublicKeysList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.votings_service.Config} returns this
 */
proto.votings_service.Config.prototype.setApiPublicKeysList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.votings_service.Config} returns this
 */
proto.votings_service.Config.prototype.addApiPublicKeys = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.votings_service.Config} returns this
 */
proto.votings_service.Config.prototype.clearApiPublicKeysList = function() {
  return this.setApiPublicKeysList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.votings_service.TxStoreBallotCopy.prototype.toObject = function(opt_includeInstance) {
  return proto.votings_service.TxStoreBallotCopy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.votings_service.TxStoreBallotCopy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.votings_service.TxStoreBallotCopy.toObject = function(includeInstance, msg) {
  var f, obj = {
    votingId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    districtId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    encryptedChoice: (f = msg.getEncryptedChoice()) && transactions_pb.TxEncryptedChoice.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.votings_service.TxStoreBallotCopy}
 */
proto.votings_service.TxStoreBallotCopy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.votings_service.TxStoreBallotCopy;
  return proto.votings_service.TxStoreBallotCopy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.votings_service.TxStoreBallotCopy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.votings_service.TxStoreBallotCopy}
 */
proto.votings_service.TxStoreBallotCopy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVotingId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDistrictId(value);
      break;
    case 3:
      var value = new transactions_pb.TxEncryptedChoice;
      reader.readMessage(value,transactions_pb.TxEncryptedChoice.deserializeBinaryFromReader);
      msg.setEncryptedChoice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.votings_service.TxStoreBallotCopy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.votings_service.TxStoreBallotCopy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.votings_service.TxStoreBallotCopy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.votings_service.TxStoreBallotCopy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVotingId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDistrictId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getEncryptedChoice();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      transactions_pb.TxEncryptedChoice.serializeBinaryToWriter
    );
  }
};


/**
 * optional string voting_id = 1;
 * @return {string}
 */
proto.votings_service.TxStoreBallotCopy.prototype.getVotingId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.votings_service.TxStoreBallotCopy} returns this
 */
proto.votings_service.TxStoreBallotCopy.prototype.setVotingId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 district_id = 2;
 * @return {number}
 */
proto.votings_service.TxStoreBallotCopy.prototype.getDistrictId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.votings_service.TxStoreBallotCopy} returns this
 */
proto.votings_service.TxStoreBallotCopy.prototype.setDistrictId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional TxEncryptedChoice encrypted_choice = 3;
 * @return {?proto.votings_service.TxEncryptedChoice}
 */
proto.votings_service.TxStoreBallotCopy.prototype.getEncryptedChoice = function() {
  return /** @type{?proto.votings_service.TxEncryptedChoice} */ (
    jspb.Message.getWrapperField(this, transactions_pb.TxEncryptedChoice, 3));
};


/**
 * @param {?proto.votings_service.TxEncryptedChoice|undefined} value
 * @return {!proto.votings_service.TxStoreBallotCopy} returns this
*/
proto.votings_service.TxStoreBallotCopy.prototype.setEncryptedChoice = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.votings_service.TxStoreBallotCopy} returns this
 */
proto.votings_service.TxStoreBallotCopy.prototype.clearEncryptedChoice = function() {
  return this.setEncryptedChoice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.votings_service.TxStoreBallotCopy.prototype.hasEncryptedChoice = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.votings_service);
