// source: exonum/runtime/auth.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var exonum_crypto_types_pb = require('../../exonum/crypto/types_pb.js');
goog.object.extend(proto, exonum_crypto_types_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.exonum.runtime.Caller', null, global);
goog.exportSymbol('proto.exonum.runtime.Caller.CallerCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.exonum.runtime.Caller = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.exonum.runtime.Caller.oneofGroups_);
};
goog.inherits(proto.exonum.runtime.Caller, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.exonum.runtime.Caller.displayName = 'proto.exonum.runtime.Caller';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.exonum.runtime.Caller.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.exonum.runtime.Caller.CallerCase = {
  CALLER_NOT_SET: 0,
  TRANSACTION_AUTHOR: 1,
  INSTANCE_ID: 2,
  BLOCKCHAIN: 3
};

/**
 * @return {proto.exonum.runtime.Caller.CallerCase}
 */
proto.exonum.runtime.Caller.prototype.getCallerCase = function() {
  return /** @type {proto.exonum.runtime.Caller.CallerCase} */(jspb.Message.computeOneofCase(this, proto.exonum.runtime.Caller.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.exonum.runtime.Caller.prototype.toObject = function(opt_includeInstance) {
  return proto.exonum.runtime.Caller.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.exonum.runtime.Caller} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.exonum.runtime.Caller.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionAuthor: (f = msg.getTransactionAuthor()) && exonum_crypto_types_pb.PublicKey.toObject(includeInstance, f),
    instanceId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    blockchain: (f = msg.getBlockchain()) && google_protobuf_empty_pb.Empty.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.exonum.runtime.Caller}
 */
proto.exonum.runtime.Caller.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.exonum.runtime.Caller;
  return proto.exonum.runtime.Caller.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.exonum.runtime.Caller} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.exonum.runtime.Caller}
 */
proto.exonum.runtime.Caller.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new exonum_crypto_types_pb.PublicKey;
      reader.readMessage(value,exonum_crypto_types_pb.PublicKey.deserializeBinaryFromReader);
      msg.setTransactionAuthor(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInstanceId(value);
      break;
    case 3:
      var value = new google_protobuf_empty_pb.Empty;
      reader.readMessage(value,google_protobuf_empty_pb.Empty.deserializeBinaryFromReader);
      msg.setBlockchain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.exonum.runtime.Caller.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.exonum.runtime.Caller.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.exonum.runtime.Caller} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.exonum.runtime.Caller.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionAuthor();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      exonum_crypto_types_pb.PublicKey.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getBlockchain();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_empty_pb.Empty.serializeBinaryToWriter
    );
  }
};


/**
 * optional exonum.crypto.PublicKey transaction_author = 1;
 * @return {?proto.exonum.crypto.PublicKey}
 */
proto.exonum.runtime.Caller.prototype.getTransactionAuthor = function() {
  return /** @type{?proto.exonum.crypto.PublicKey} */ (
    jspb.Message.getWrapperField(this, exonum_crypto_types_pb.PublicKey, 1));
};


/**
 * @param {?proto.exonum.crypto.PublicKey|undefined} value
 * @return {!proto.exonum.runtime.Caller} returns this
*/
proto.exonum.runtime.Caller.prototype.setTransactionAuthor = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.exonum.runtime.Caller.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.exonum.runtime.Caller} returns this
 */
proto.exonum.runtime.Caller.prototype.clearTransactionAuthor = function() {
  return this.setTransactionAuthor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.exonum.runtime.Caller.prototype.hasTransactionAuthor = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 instance_id = 2;
 * @return {number}
 */
proto.exonum.runtime.Caller.prototype.getInstanceId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.exonum.runtime.Caller} returns this
 */
proto.exonum.runtime.Caller.prototype.setInstanceId = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.exonum.runtime.Caller.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.exonum.runtime.Caller} returns this
 */
proto.exonum.runtime.Caller.prototype.clearInstanceId = function() {
  return jspb.Message.setOneofField(this, 2, proto.exonum.runtime.Caller.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.exonum.runtime.Caller.prototype.hasInstanceId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Empty blockchain = 3;
 * @return {?proto.google.protobuf.Empty}
 */
proto.exonum.runtime.Caller.prototype.getBlockchain = function() {
  return /** @type{?proto.google.protobuf.Empty} */ (
    jspb.Message.getWrapperField(this, google_protobuf_empty_pb.Empty, 3));
};


/**
 * @param {?proto.google.protobuf.Empty|undefined} value
 * @return {!proto.exonum.runtime.Caller} returns this
*/
proto.exonum.runtime.Caller.prototype.setBlockchain = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.exonum.runtime.Caller.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.exonum.runtime.Caller} returns this
 */
proto.exonum.runtime.Caller.prototype.clearBlockchain = function() {
  return this.setBlockchain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.exonum.runtime.Caller.prototype.hasBlockchain = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.exonum.runtime);
